<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CommonRoot Condition="'$(CommonRoot)' == ''">$(MSBuildThisFileDirectory)..\Common</CommonRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Aegis.Diagnostics.UnitTests\**\*.cs" />
    <None Remove="Aegis.Diagnostics.UnitTests\**\*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(CommonRoot)\Common.Diagnostics\Common.Diagnostics.csproj" />
  </ItemGroup>
</Project>
